apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal
  labels:
    app: job-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
      - name: job-portal
        image: ghcr.io/your-username/job-portal:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: job-portal-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5