apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal
  labels:
    app: job-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
      - name: job-portal
        image: ghcr.io/your-username/job-portal:latest
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5